package com.middleton.scott.cmboxing.other

object Constants {

    const val ACTION_START_OR_RESUME_STRUCTURED_SERVICE = "ACTION_START_OR_RESUME_STRUCTURED_SERVICE"
    const val ACTION_START_OR_RESUME_RANDOM_SERVICE = "ACTION_START_OR_RESUME_RANDOM_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"

    const val NOTIFICATION_CHANNEL_ID = "workout_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Workout"
    const val NOTIFICATION_ID = 1

    const val ACTION_SHOW_WORKOUT_SCREEN = "ACTION_SHOW_WORKOUT_SCREEN"
    const val REQUEST_AUDIO_PERMISSION_CODE = 1

    const val MIN_PASSWORD_LENGTH = 7

    const val GOOGLE_SIGN_IN = 111

    const val PRODUCT_UNLIMITED_COMMANDS = "unlimited_commands_pro"
}